
---
ansible_connection: local
openshift_cluster_content:
- object: app-builds
  content:
  - name: noun-app-build
    template: "{{ playbook_dir }}/openshift-templates/s2i-app-build/template-no-secrets.yaml"
    params: "{{ playbook_dir }}/params/noun-service/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - npm-build
  - name: adjective-app-build
    template: "{{ playbook_dir }}/openshift-templates/s2i-app-build/template-no-secrets.yaml"
    params: "{{ playbook_dir }}/params/adjective-service/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - spring-build
  - name: ui-app-build
    template: "{{ playbook_dir }}/openshift-templates/s2i-app-build/template-no-secrets.yaml"
    params: "{{ playbook_dir }}/params/ui-service/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - vertx-build
  - name: kafka-app-build
    template: "{{ playbook_dir }}/openshift-templates/s2i-app-build/template-no-secrets.yaml"
    params: "{{ playbook_dir }}/params/kafka-service/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - vertx-build
- object: dev-stage
  content:
  - name: noun-app
    template: "{{ playbook_dir }}/openshift-templates/node-app-deploy/template.yaml"
    params: "{{ playbook_dir }}/params/noun-service/deploy"
    namespace: "{{ dev_namespace }}"
    tags:
    - npm-deploy
  - name: adjective-app
    template: "{{ playbook_dir }}/openshift-templates/spring-app-deploy/template.yaml"
    params: "{{ playbook_dir }}/params/adjective-service/deploy"
    namespace: "{{ dev_namespace }}"
    tags:
    - java-deploy
  - name: ui-app
    template: "{{ playbook_dir }}/openshift-templates/vertx-app-deploy/template.yaml"
    params: "{{ playbook_dir }}/params/ui-service/deploy"
    namespace: "{{ dev_namespace }}"
    tags:
    - vertx-deploy
  - name: kafka-app
    template: "{{ playbook_dir }}/openshift-templates/vertx-app-deploy/template.yaml"
    params: "{{ playbook_dir }}/params/kafka-service/deploy"
    namespace: "{{ dev_namespace }}"
    tags:
    - vertx-deploy
  - name: fabric8-rolebinding
    template: "{{ playbook_dir }}/openshift-templates/fabric8-role-bindings/template.yaml"
    params: "{{ playbook_dir }}/params/java-app/fabric8_dev"
    namespace: "{{ dev_namespace }}"
    tags:
    - java-deploy
- object: test-stage
  content:
  - name: noun-app
    template: "{{ playbook_dir }}/openshift-templates/node-app-deploy/template.yaml"
    params: "{{ playbook_dir }}/params/noun-service/deploy"
    namespace: "{{ test_namespace }}"
    tags:
    - npm-deploy
  - name: adjective-app
    template: "{{ playbook_dir }}/openshift-templates/spring-app-deploy/template.yaml"
    params: "{{ playbook_dir }}/params/adjective-service/deploy"
    namespace: "{{ test_namespace }}"
    tags:
    - java-deploy
  - name: ui-app
    template: "{{ playbook_dir }}/openshift-templates/vertx-app-deploy/template.yaml"
    params: "{{ playbook_dir }}/params/ui-service/deploy"
    namespace: "{{ test_namespace }}"
    tags:
    - vertx-deploy
  - name: kafka-app
    template: "{{ playbook_dir }}/openshift-templates/vertx-app-deploy/template.yaml"
    params: "{{ playbook_dir }}/params/kafka-service/deploy"
    namespace: "{{ test_namespace }}"
    tags:
    - vertx-deploy
  - name: fabric8-rolebinding
    template: "{{ playbook_dir }}/openshift-templates/fabric8-role-bindings/template.yaml"
    params: "{{ playbook_dir }}/params/java-app/fabric8_dev"
    namespace: "{{ test_namespace }}"
    tags:
    - java-deploy