---
ansible_connection: local
openshift_cluster_content:
## Create OpenShift Projects/Namespaces
- object: projectrequest
  content:
  - name: ci-cd
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    template_action: create
    params: "{{ playbook_dir }}/params/projectrequests/ci-cd"
    tags:
    - projects
  - name: dev
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    template_action: create
    params: "{{ playbook_dir }}/params/projectrequests/dev"
    tags:
    - projects
  - name: demo
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
    template_action: create
    params: "{{ playbook_dir }}/params/projectrequests/test"
    tags:
    - projects
- object: rolebindings
  content:
  - name: dev-default
    template: "{{ playbook_dir }}/openshift-templates/default-user-view-role/template.yaml"
    params: "{{ playbook_dir }}/params/default-user-view-role/dev"
    namespace: labs-dev
  - name: test-default
    template: "{{ playbook_dir }}/openshift-templates/default-user-view-role/template.yaml"
    params: "{{ playbook_dir }}/params/default-user-view-role/test"
    namespace: labs-test
  - name: dev-jenkins
    template: "{{ playbook_dir }}/openshift-templates/jenkins-rolebindings/template.yaml"
    params: "{{ playbook_dir }}/params/jenkins-rolebindings/dev"
    namespace: labs-dev
  - name: test-jenkins
    template: "{{ playbook_dir }}/openshift-templates/jenkins-rolebindings/template.yaml"
    params: "{{ playbook_dir }}/params/jenkins-rolebindings/test"
    namespace: labs-test